title: Bobby Nguy
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: >
  Over 9 years of experience in data analytics, visualizations, predictive modeling and data pipelines. Skilled in working with business teams such as Sales, Marketing and Customer Success to drive product success.
  Extensive experience leading data initiatives in startups and in Microsoft. Possess a Masters of Statistics degree from Stanford.
  <br><br>
  Most recently worked in an early-stage startup building LLM applications.
  <br><br>
  <a href="https://www.linkedin.com/in/bobby-nguy">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
