title: Bobby Nguy
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: >
  <br><br>
  Over 9 years of experience driving business outcomes through product analytics, statistical modeling and machine learning. Helped launch the Deal Insights product at Outreach and the Office usage segmentation model at Microsoft.
  <br><br>
  <a href="https://www.linkedin.com/in/bobby-nguy">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
